### ISSUE TITLE
vagrant-openstack-provider version installed by vagrant is 0.3.2

### ISSUE THREAD

**Issue by phiche** [ggiamarchi/vagrant-openstack-provider#233]
For some after a ```vagrant plugin install vagrant-openstack-provider``` I end up with version 0.3.2. I see the latest version in ruby gems is 0.6.1 however. 

The problem with 0.3.2 is that it breaks ```vagrant login``` with the following error:
```
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/login/client.rb:82:in `rescue in with_error_handling': uninitialized constant VagrantPlugins::LoginCommand::Client::RestClient (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/login/client.rb:81:in `with_error_handling'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/login/client.rb:41:in `login'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/login/command.rb:55:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

I hope the latest version fixes this but it is not upgrading through vagrant as expected.

I could install the ruby gem separately and copy it into ~/.vagrant.d/gems/gems/ but this feels like a bit of a hack. Why am I not getting the right version?

**Comment by julienvey** [comment]
@phiche Did you you try `vagrant plugin update vagrant-openstack-provider` ?

**Comment by phiche** [comment]
Yep
```
16:59 gems → vagrant plugin update vagrant-openstack-provider
Updating plugins: vagrant-openstack-provider. This may take a few minutes...
All plugins are up to date.
17:00 gems → vagrant plugin list
oscar (0.4.2)
vagrant-aws (0.6.0)
vagrant-azure (1.1.1)
vagrant-hostmanager (1.5.0)
vagrant-openstack-provider (0.3.2)
vagrant-s3auth (1.1.0)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)
vagrant-vbguest (0.10.0)
```

**Comment by ggiamarchi** [comment]
@phiche I don't manage to reproduce your problem. Can you give a try with the latest vagrant `1.7.2` and the latest vagrant-openstack-provider `0.6.1` ?

To force the latest version of vagrant-openstack-provider, you can try to uninstall and reinstall it.

```
vagrant plugin uninstall vagrant-openstack-provider
vagrant plugin install vagrant-openstack-provider
```

**Comment by phiche** [comment]
I am running the latest version. Uninstalling and reinstalling gives me version 0.3.2 again.
```
19:12 gems → vagrant --version
Vagrant 1.7.2
19:21 gems → ruby --version
ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]
20:22 gems → vagrant plugin uninstall vagrant-openstack-provider
Uninstalling the 'vagrant-openstack-provider' plugin...
20:25 gems → vagrant plugin install vagrant-openstack-provider
Installing the 'vagrant-openstack-provider' plugin. This can take a few minutes...
Installed the plugin 'vagrant-openstack-provider (0.3.2)'!
```
I actually tried to fudge to copy the gem manually into the plugin into the ~/.vagrant.d/gems/gems directory but there is obviously a bit more to it than that.

Maybe this is a vagrant problem?

**Comment by ggiamarchi** [comment]
And what if you force the version like this ?

```
vagrant plugin install vagrant-openstack-provider --plugin-version 0.6.1
```

**Comment by phiche** [comment]
Now we found the problem!
```
20:30 gems → vagrant plugin install vagrant-openstack-provider --plugin-version 0.6.1
Installing the 'vagrant-openstack-provider --version '0.6.1'' plugin. This can take a few minutes...
The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "json":
  In Gemfile:
    vagrant-azure (>= 0) ruby depends on
      azure (= 0.6.3) ruby depends on
        json (~> 1.8) ruby

    vagrant-openstack-provider (= 0.6.1) ruby depends on
      json (1.7.7)
```
I remove vagrant-azure and upgraded vagrant-openstack-provider to 0.6.1 which also fixed my vagrant login issue.

Thanks for the support!

**Comment by jayunit100** [comment]
We've seen this on fedora 22 also, any thoughts on the best way to work around this ?  Is there a "reinstall xyz" solution?

**Comment by eparis** [comment]
```
$ vagrant plugin install vagrant-openstack-provider --plugin-version 0.6.1
Installing the 'vagrant-openstack-provider --version '0.6.1'' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.7.7), and Bundler cannot continue.
Make sure that `gem install json -v '1.7.7'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150707-16067-1fjctt.rb extconf.rb 
creating Makefile

make "DESTDIR=" clean
rm -f 
rm -f generator.so  *.o  *.bak mkmf.log .*.time

make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -DJSON_GENERATOR    -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -fPIC -O3 -Wall -O0 -ggdb -m64 -o generator.o -c generator.c
In file included from /usr/include/stdio.h:27:0,
                 from /usr/include/ruby/defines.h:26,
                 from /usr/include/ruby/ruby.h:29,
                 from /usr/include/ruby.h:33,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
Makefile:238: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/eparis/.vagrant.d/gems/gems/json-1.7.7 for inspection.
Results logged to /home/eparis/.vagrant.d/gems/extensions/x86_64-linux/json-1.7.7/gem_make.out
```

For me its json 1.7.7 vs ruby 2.2

**Comment by eparis** [comment]
https://github.com/flori/json/issues/229

json 1.8.4 works with ruby 2.2...
